obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.1
inflation_radius: 0

<<<<<<< HEAD


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
=======
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
>>>>>>> c0c82179b96779cd8068889092fa84e68157130e
