obstacle_range: 2
raytrace_range: 2
robot_radius: 0.1
inflation_radius: 0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
