#!/usr/bin/env python

import rospy
from std_srvs.srv import Trigger, TriggerRequest
from sensor_msgs.msg import JointState
from control_msgs.msg import FollowJointTrajectoryGoal
from trajectory_msgs.msg import JointTrajectoryPoint


import hello_helpers.hello_misc as hm
import math


class Manipulation_t1(hm.HelloNode):

    def __init__(self):
        hm.HelloNode.__init__(self)

	self.rate = 7.0
	

	self.random_p1 = {'wrist_extension':2.0, 'joint_lift': 2.0}	#44.5in, 30in
	self.random_p2 = {'wrist_extension':0.0, 'joint_lift': 0.0}    #4.5in, 10in


	
      

    def command_random(self):

	
	self.move_to_pose(self.random_p1)

	self.trajectory_client.wait_for_result()

	self.move_to_pose(self.random_p2)

	self.trajectory_client.wait_for_result()
	
	

    def begin_test(self):

	rate = rospy.Rate(self.rate)
	self.command_random()
	

    def main(self):
	hm.HelloNode.main(self,'manipulation_test1', 'manipulation_test1', wait_for_first_pointcloud=False)

if __name__ == '__main__':

    try:
        node = Manipulation_t1()
		node.main()
		node.begin_test()
	
    except KeyboardInterrupt:
        rospy.loginfo('interrupt received bro!!! Gotcha!')
